# Generated by Django 4.2.3 on 2023-07-10 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_users_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('back end', 'Back End'), ('front end', 'Front End'), ('iOS', 'IOS'), ('Android', 'Android')], max_length=10)),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.users')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
