# Generated by Django 4.2.2 on 2023-07-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
